// <auto-generated />
namespace RegexAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update6Matt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update6Matt));
        
        string IMigrationMetadata.Id
        {
            get { return "202301201421328_Update6Matt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
